server:
  port: 8082
  servlet:
    context-path: /user

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_api?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: postgres
    password: admin 
    driver-class-name: org.postgresql.Driver
    
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    virtual-host: /
#    ssl:
#      enabled: false
  
  jpa:
    hibernate:
      #ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
flyway:
  locations: classpath:db/migration
  baseline-on-migrate: true
  
auth:
  jwtSecret: 817cff65-0402-46fb-ba27-7c6809959fd1
  jwtExpiration: 300000
